version: '2.2'
services:

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    image: rgordeev/chat
    volumes:
    - chat-logs:/usr/share/chat/logs
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SERVER_PORT=8080
    - JAVA_OPTS=-Xmx300m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
    - 8080:8080
    - 5005:5005
    expose:
    - 8080
    - 5005
    networks:
    - backend

networks:
  backend:
    driver: bridge

volumes:
  chat-logs:
