spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: chat
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML

logging:
  level:
    org.springframework.web: DEBUG
    ru.rgordeev.chat: DEBUG

server:
  servlet:
    session:
      cookie:
        http-only: true
